// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppxazmeqyhbgnflbjgci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBweGF6bWVxeWhiZ25mbGJqZ2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDAzOTMsImV4cCI6MjA3MjcxNjM5M30.jXHBjnavaiKZQK1o11QTBUCXicgwUShWpQzIgdPqEqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});